defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

run:
  dir: ${paths.run_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}
sweep:
  dir: ${paths.run_dir}/multi/${now:%Y-%m-%d}/${now:%H-%M-%S}
  subdir: ${hydra.job.num}

job_logging:
  handlers:
    file:
      filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log